# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'UpGradTest' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for UpGradTest
pod 'Kingfisher'

  target 'UpGradTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'UpGradTestUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
